ALTER TABLE EXAMINABLE_COURSE
    ADD COURSE_TITLE VARCHAR2(50);

ALTER TABLE EXAMINABLE_COURSE
    ADD COURSE_ID NUMBER(7,0) NOT NULL ENABLE;

ALTER TABLE EXAMINABLE_COURSE
    ADD SCHOOL_WEIGHT_PERCENT NUMBER(3,0);

ALTER TABLE EXAMINABLE_COURSE
    ADD EXAM_WEIGHT_PERCENT NUMBER(3,0);

