ALTER TABLE EXAMINABLE_COURSE
    ADD COURSE_TITLE VARCHAR2(50);

ALTER TABLE EXAMINABLE_COURSE
    ADD SCHOOL_WEIGHT_PERCENT NUMBER(3,0);

ALTER TABLE EXAMINABLE_COURSE
    ADD EXAM_WEIGHT_PERCENT NUMBER(3,0);

ALTER TABLE EXAMINABLE_COURSE
    MODIFY (EXAMINABLE_START VARCHAR2(7));

ALTER TABLE EXAMINABLE_COURSE
    MODIFY (EXAMINABLE_END VARCHAR2(7));

ALTER TABLE EXAMINABLE_COURSE
    MODIFY (OPTIONAL_START VARCHAR2(7));

ALTER TABLE EXAMINABLE_COURSE
    MODIFY (OPTIONAL_END VARCHAR2(7));

