ALTER TABLE EXAMINABLE_COURSE
    DROP COLUMN COURSE_CODE;

ALTER TABLE EXAMINABLE_COURSE
    DROP COLUMN COURSE_LEVEL;

ALTER TABLE EXAMINABLE_COURSE
    ADD COURSE_ID NUMBER(7,0) NOT NULL ENABLE;

ALTER TABLE EXAMINABLE_COURSE
    ADD CONSTRAINT "EXM_CRS_COURSE_ID_FK" FOREIGN KEY ("COURSE_ID")
        REFERENCES "COREG"."CRSE_COURSES" ("CRS_ID") ENABLE;