ALTER TABLE COURSE_REQUIREMENT
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE COURSE_REQUIREMENT
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE COURSE_RESTRICTION
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE COURSE_RESTRICTION
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE EQUIVALENT_OR_CHALLENGE_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE EQUIVALENT_OR_CHALLENGE_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE EXAM_SPECIAL_CASE_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE EXAM_SPECIAL_CASE_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE EXAMINABLE_COURSE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE EXAMINABLE_COURSE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE FINE_ARTS_APPLIED_SKILLS_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE FINE_ARTS_APPLIED_SKILLS_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE STATUS_EVENT
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE STATUS_EVENT
    MODIFY UPDATE_USER VARCHAR2(100);





