UPDATE EXAMINABLE_COURSE SET
    SCHOOL_WEIGHT_PERCENT_PRE_1989 = '50',
    EXAM_WEIGHT_PERCENT_PRE_1989 = '50'
WHERE
    (COURSE_CODE = 'ALG' AND COURSE_LEVEL = '12')
OR
    (COURSE_CODE = 'BI' AND COURSE_LEVEL = '12')
OR
    (COURSE_CODE = 'CH' AND COURSE_LEVEL = '12')
OR
    (COURSE_CODE = 'COM' AND COURSE_LEVEL = '12')
OR
    (COURSE_CODE = 'EN' AND COURSE_LEVEL = '12')
OR
    (COURSE_CODE = 'FR' AND COURSE_LEVEL = '12')
OR
    (COURSE_CODE = 'FRAL' AND COURSE_LEVEL = '12')
OR
    (COURSE_CODE = 'GE' AND COURSE_LEVEL = '12')
OR
    (COURSE_CODE = 'GEO' AND COURSE_LEVEL = '12')
OR
    (COURSE_CODE = 'GEOL' AND COURSE_LEVEL = '12')
OR
    (COURSE_CODE = 'GEOLF' AND COURSE_LEVEL = '12')
OR
    (COURSE_CODE = 'HI' AND COURSE_LEVEL = '12')
OR
    (COURSE_CODE = 'LA' AND COURSE_LEVEL = '12')
OR
    (COURSE_CODE = 'LIT' AND COURSE_LEVEL = '12')
OR
    (COURSE_CODE = 'PH' AND COURSE_LEVEL = '12')
OR
    (COURSE_CODE = 'SP' AND COURSE_LEVEL = '12');