-- Listed tables are moved to student schema
DROP TABLE "STUDENT_COURSE" CASCADE CONSTRAINTS;;
DROP TABLE "STUDENT_COURSE_EXAM" CASCADE CONSTRAINTS;;
DROP TABLE "EQUIVALENT_OR_CHALLENGE_CODE" CASCADE CONSTRAINTS;
DROP TABLE "EXAM_SPECIAL_CASE_CODE" CASCADE CONSTRAINTS;
DROP TABLE "FINE_ARTS_APPLIED_SKILLS_CODE" CASCADE CONSTRAINTS;
