-- EXAMINABLE_COURSES definition

CREATE TABLE "EXAMINABLE_COURSES"
(	"COURSE_ID" VARCHAR2(4),
     "EXAMINABLE_START" DATE,
     "EXAMINABLE_END" DATE,
     "OPTIONAL_START" DATE,
     "OPTIONAL_END" DATE,
     "CREATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT "COURSE_ID_PK" PRIMARY KEY ("COURSE_ID")
         USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;
