name: BuildToDev

env:
  APP_NAME: educ-grad-course-api

  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}

  IMAGE_TAGS: ""
  IMAGE_NAME: $APP_NAME

  DOCKER_ARTIFACTORY_REPO: docker-remote.artifacts.developer.gov.bc.ca
  ARTIFACTORY_REPO: artifacts.developer.gov.bc.ca
  
  REPO_NAME: $APP_NAME
  JOB_NAME: "master"
  APP_NAME_FULL: $APP_NAME"-master"
  TAG: "latest"
  TARGET_ENV: "dev"
  MIN_REPLICAS: "1"
  MAX_REPLICAS: "1"
  MIN_CPU: "50m"
  MAX_CPU: "500m"
  MIN_MEM: "500Mi"
  MAX_MEM: "2048Mi"

on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  push:
    branches: ['develop/chris']

jobs:
  openshift-ci-cd:
    name: Build and deploy to OpenShift
    runs-on: ubuntu-latest
    environment: test

    steps:
     - name: Check env
       run: |
         echo "APP_NAME="${{ env.APP_NAME }} \
         echo "IMAGE_NAME"=${{ env.IMAGE_NAME }}
